#!/usr/bin/env bash
#
# ESC-047 / FOLLOW-808 — the served SDK bundles must be BUILT, never committed.
#
# History this gate exists to prevent repeating: `apps/control-plane/public/sdk.js` was a
# hand-built, hand-committed artifact. It last moved 2026-05-29 (`4bdaf58c`);
# `public/estalara-detect.iife.js` last moved 2026-06-17 (`43ad8496`). In between, ~76
# tickets touching `packages/sdk` merged — every one green in CI, DONE in the queue, and
# absent from `admin.estalara.com/sdk.js`, which served the frozen May bytes throughout.
# Nothing in the repo could detect that, because a stale committed binary looks exactly
# like a fresh one.
#
# Two ways the fix can silently rot, so this gate checks both:
#   1. Someone re-commits an artifact. It would then shadow the generated file in the
#      working tree and re-open the staleness class.
#   2. The generator stops being wired into the build. Then Vercel deploys a `public/`
#      with no bundle at all and every tenant's <script src> 404s — worse than stale.
#
# Deliberately NOT checked: byte-equality of a rebuilt bundle against anything. There is
# no committed baseline to compare to any more, which is the entire point.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

GENERATOR="apps/control-plane/scripts/copy-sdk-bundle.mjs"
ARTIFACTS=(
  "apps/control-plane/public/sdk.js"
  "apps/control-plane/public/estalara-detect.iife.js"
)

fail=0

echo "=== Served SDK bundles: built, never committed (ESC-047) ==="

# ── 1. No artifact may be tracked by git ─────────────────────────────────────
for artifact in "${ARTIFACTS[@]}"; do
  if git ls-files --error-unmatch "$artifact" >/dev/null 2>&1; then
    echo "FAIL: '$artifact' is TRACKED by git."
    echo "      It must be generated by '$GENERATOR' on every build, not committed —"
    echo "      a committed copy silently freezes what tenants load (ESC-047)."
    echo "      Fix: git rm --cached '$artifact' (it is already in .gitignore)."
    fail=1
  else
    echo "OK:   $artifact is not tracked."
  fi
done

# ── 2. The generator must exist and be wired into the control-plane build ────
if [[ ! -f "$GENERATOR" ]]; then
  echo "FAIL: generator '$GENERATOR' is missing — nothing would produce the bundles."
  fail=1
else
  echo "OK:   generator present."

  if ! grep -q "copy-sdk-bundle.mjs" apps/control-plane/package.json; then
    echo "FAIL: '$GENERATOR' is not referenced by apps/control-plane/package.json's build script."
    echo "      Vercel builds with 'turbo run build --filter=@estalara/control-plane'; if the"
    echo "      generator is not in that script, public/ deploys empty and every tenant 404s."
    fail=1
  else
    echo "OK:   generator wired into the control-plane build script."
  fi
fi

# ── 3. The artifacts must be declared Turbo outputs ──────────────────────────
# Without this, a Turbo cache HIT replays the build logs but restores nothing into
# public/ — the deploy then ships a control-plane with no SDK bundle. Verified
# reproducible: delete the artifacts, re-run without --force, and they come back only
# because they are listed here.
TURBO_CONFIG="apps/control-plane/turbo.json"
if [[ ! -f "$TURBO_CONFIG" ]]; then
  echo "FAIL: '$TURBO_CONFIG' is missing — the bundles would not be Turbo build outputs,"
  echo "      so a cache hit would leave public/ empty."
  fail=1
else
  for artifact in "${ARTIFACTS[@]}"; do
    basename_only="${artifact#apps/control-plane/}"
    if ! grep -q "$basename_only" "$TURBO_CONFIG"; then
      echo "FAIL: '$basename_only' is not declared as a build output in $TURBO_CONFIG."
      echo "      A Turbo cache hit would then restore .next/ but not the bundle."
      fail=1
    else
      echo "OK:   $basename_only declared as a Turbo build output."
    fi
  done
fi

echo
if [[ "$fail" -ne 0 ]]; then
  echo "Served-bundle gate FAILED. See ESC-047 / FOLLOW-808."
  exit 1
fi

echo "Served-bundle gate passed — bundles are build-generated and cache-safe."
